---
title: "Accessing annotations in Bioconductor"
author: "[Michael Love](http://mikelove.github.io)"
output: html_document
---

Note that *AnnotationHub* creates a hidden folder in your home
directory, `~/.AnnotationHub` which accumulates the data objects you
download with the package. 

```{r}
library("AnnotationHub")
ah <- AnnotationHub()
```

```{r eval=FALSE}
display(ah)
```

Search for species "Homo sapiens" and description "ChIP-seq"

```{r}
ah["AH28856"]
peaks <- ah[["AH28856"]]
peaks
seqinfo(peaks)
```

Let's look up human-specific information

```{r}
orgs <- subset(ah, ah$rdataclass == "OrgDb")
orgdb <- query(orgs, "Homo sapiens")[[1]]
orgdb
```

```{r}
columns(orgdb)
```

one of my example genes: SFTPB
https://gtexportal.org/home/gene/SFTPB


```{r}
select(orgdb, "SFTPB", "GENENAME", "SYMBOL")
go <- select(orgdb, "SFTPB", "GO", "SYMBOL")
go <- go[go$ONTOLOGY == "BP",] # biological processes
```

```{r}
library(GO.db)
columns(GO.db)
go2 <- select(GO.db, go$GO, c("TERM","DEFINITION"), "GOID")
split(go2, seq_len(nrow(go2)))
```

```{r}
select(orgdb, "NR3C1", "GENENAME", "SYMBOL")
go <- select(orgdb, "NR3C1", "GO", "SYMBOL")
go <- go[go$ONTOLOGY == "BP",] # biological processes
go2 <- select(GO.db, go$GO, c("TERM","DEFINITION"), "GOID")
split(go2, seq_len(nrow(go2)))
```
